version: 0.0
os: linux
files:
  - source: ./webapp.jar
    destination: /tmp
  - source: ./cloudwatch-config.json
    destination: /tmp
hooks:
  ApplicationStop:
    - location: scripts/stopapp.sh
      timeout: 30
      runas: ubuntu
  AfterInstall:
    - location: scripts/startcloudwatchagent.sh
      timeout: 30
      runas: ubuntu
  ApplicationStart:
    - location: scripts/startapp.sh
      timeout: 60
      runas: ubuntu
    
