version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
      - image: circleci/mysql:8.0.4
        environment:
          MYSQL_ROOT_PASSWORD: mzc961031
          MYSQL_DATABASE: cloudDB
          MYSQL_USER: root
          MYSQL_PASSWORD: mzc961031

    steps:
      - checkout
      - run:
      # Our primary container isn't MYSQL so run a sleep command until it's ready.
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          name: Install MySQL CLI; Import dummy data; run an example query
          command: |
            sudo apt-get install default-mysql-client
            mysql -h 127.0.0.1 -u user -ppassw0rd cloudDB < sql-data/dummy.sql
          
  pr_check:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - run:
          name: compile
          working_directory: ~/project/RunUt
          command: mvn compile
      - run:
          name: test
          working_directory: ~/project/RunUt
          command: mvn test

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
#   pr-check-workflow:
#     jobs:
#       - pr_check
