version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
  pr_check:
    steps:
      - run:
          name: compile
          command: |
            echo 'compile'
      - run:
          name: unit test
          command: echo 'unit test'

workflows:
  version: 2
  pr-check-workflow:
    jobs:
      - pr_check
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
