version: 2
jobs:          
  pr_check:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: 'mzc961031'
          MYSQL_DATABASE: cloudDB
          MYSQL_ROOT_HOST: 127.0.0.1
          MYSQL_USER: root
    steps:
      - checkout
      - run:
          name: compile
          working_directory: ~/project/RunUt
          command: mvn compile
      - run:
          name: test
          working_directory: ~/project/RunUt
          command: mvn test

workflows:
  version: 2
  pr-check-workflow:
    jobs:
      - pr_check
