version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
  pr_check:
    steps:
      - run:
          name: compile
          command: |
            echo 'compile'
      - run:
          name: unit test
          command: echo 'unit test'

workflows:
  version: 2
  pr-check-workflow:
    jobs:
      - pr_check
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
