version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-stretch

    steps:
      - checkout # check out source code to working directory

      - restore_cache:
          working_directory: ~/RunUt
          key: RunUt-{{ checksum "pom.xml" }}
      
      - run: 
          command: |
              pwd
#             mvn dependency:go-offline
      
      - save_cache: # saves the project dependencies
          paths:
            - ~/.m2
          key: RunUt-{{ checksum "pom.xml" }}
          path: ~/RunUt
      
#       - run:
#           command: mvn test # run the actual tests
      
      - store_test_results: # uploads the test metadata from the `target/surefire-reports` directory so that it can show up in the CircleCI dashboard. 
      # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: target/surefire-reports
          
  pr_check:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - run:
          name: compile
          command: |
          working_directory: ~/project/RunUt
            ls
      - run:
          name: test
          command: |
            echo "try all tests"

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
  pr-check-workflow:
    jobs:
      - pr_check
