version: 2.1
executors:
  deploy_executor:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
      - image: circleci/mysql:5.7
    working_directory: ~/project/RunUt
    environment:
      MYSQL_ROOT_PASSWORD: "mzc961031"
      MYSQL_DATABASE: cloudDB
      MYSQL_ROOT_HOST: 127.0.0.1
      MYSQL_USER: root

jobs:
  mvntest:
    executor: deploy_executor
    working_directory: ~/project/RunUt
    steps:
      - checkout
      - run:
          name: maven test
          command: |
            ls -a
            mvn test

  upload_deploy:
    executor: deploy_executor
    steps:
      - checkout
      - run:
          name: build artifact
          command: mvn package
      - run:
          name: move artifact and scripts appspec
          command: |
            mkdir ~/project/bundle
            mv ~/project/RunUt/target/webapp.jar ~/project/bundle
            mv ~/project/appspec ~/project/bundle
            mv -r ~/project/scipts ~/poject/bundle
      - run:
          name: install aws
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
      - run:
          name: configure aws profile
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY --profile circleci
            aws configure set aws_secret_access_key $AWS_SECRET_KEY --profile circleci
            aws configure set region $AWS_REGION --profile circleci
      - run:
          name: upload to s3
          command: aws deploy push --application-name $CODEDEPLOY_APPNAME --s3-location s3://$CODEDEPLOY_BUCKETNAME/$BUCKET_KEYNAME --source ~/project/bundle --profile circleci
      - run:
          name: create deploy
          command: aws deploy create-deployment --application-name $CODEDEPLOY_APPNAME --s3-location bucket=$CODEDEPLOY_BUCKETNAME,bundleType=zip,key=$BUCKET_KEYNAME --deployment-group-name $CODEDEPLOY_GROUPNAME --description "cicd deploy" --profile circleci
    
  pr_check:
    executor: deploy_executor
    steps:
      - checkout
      - run:
          name: compile
          command: mvn compile
      - run:
          name: test
          command: mvn test

workflows:
  build-workflow:
    jobs:
      - mvntest
      - upload_deploy:
          requires:
            - mvntest
  pr-check-workflow:
    jobs:
      - pr_check
