version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run: echo "A first hello"
  pr_check:
    docker:
      - image: circleci/openjdk:8u181-jdk
    steps:
      - run:
          name: new test
          command:
          ls -l
      

workflows:
  version: 2
  pr-check-workflow:
    jobs:
      - pr_check
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
